### ISSUE TITLE
Crashes when trying to install a certain vpk

### ISSUE THREAD

**Issue by JaegerFox** [RealYoti/VitaShell#5]
I am here because I have had no problem with your fork when installing some VPKs but when I want to install NetStream, Vitashell crashes and closes the application... 
I already discussed this with Graphene and he said it's not an issue related to him, so that's why I'm here.

Thanks..

**Comment by RealYoti** [comment]
Use this build until v2.05 released.
[VitaShell-2.04-fix1.zip](https://github.com/RealYoti/VitaShell/files/10373195/VitaShell-2.04-fix1.zip)

**Comment by JaegerFox** [comment]
that solved the problem but a simple update did not work (using molecular shell) I had to uninstall and install vitashell again.
